# Vue.js 项目的 CI/CD 工作流 - 清洁安装依赖、缓存、构建源代码
# 更多信息请参考: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Vue.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # 支持的 Node.js 版本，参考: https://nodejs.org/en/about/releases/

    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置 Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: 安装依赖
      run: npm ci
      
    - name: 构建项目
      run: npm run build
      
    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      if: matrix.node-version == '20.x'
      with:
        name: vue-build-artifacts
        path: dist/
        retention-days: 7
